// Generated by rust-zmanim-test-generator
// https://github.com/YSCohen/rust-zmanim-test-generator
// This file is part of rust-zmanim, licensed under LGPL-2.1

//! this is a set of tests for the *shaah zmanis* methods of
//! [ComplexZmanimCalendar](rust_zmanim::complex_zmanim_calendar::ComplexZmanimCalendar),
//! using sea-level calculations.

mod test_helper;
use jiff::{RoundMode, SignedDurationRound, Unit};
use std::iter::zip;

#[test]
fn test_shaah_zmanis_alos_16_1_to_tzeis_3_7() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H3M18.553S",
        "PT1H3M54.368S",
        "PT1H3M41.167S",
        "PT1H3M41.83S",
        "PT1H3M38.308S",
        "PT1H8M27.27S",
        "PT1H9M2.837S",
        "PT1H4M36.885S",
        "PT1H9M22.759S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_alos_16_1_to_tzeis_3_7().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_alos_16_1_to_tzeis_3_8() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H3M21.199S",
        "PT1H3M56.747S",
        "PT1H3M43.608S",
        "PT1H3M44.319S",
        "PT1H3M57.725S",
        "PT1H8M29.366S",
        "PT1H9M4.976S",
        "PT1H4M39.059S",
        "PT1H9M24.919S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_alos_16_1_to_tzeis_3_8().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_19_8_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H11M57.265S",
        "PT1H11M41.331S",
        "PT1H11M40.103S",
        "PT1H11M50.323S",
        "None",
        "PT1H15M26.376S",
        "PT1H16M12.067S",
        "PT1H11M44.389S",
        "PT1H16M37.302S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_19_8_degrees().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_18_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H10M23.015S",
        "PT1H10M16.641S",
        "PT1H10M13.227S",
        "PT1H10M21.645S",
        "None",
        "PT1H14M9.606S",
        "PT1H14M53.212S",
        "PT1H10M26.918S",
        "PT1H15M17.339S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_18_degrees().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_26_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H17M23.865S",
        "PT1H16M33.504S",
        "PT1H16M40.05S",
        "PT1H16M56.844S",
        "None",
        "PT1H19M52.748S",
        "PT1H20M46.485S",
        "PT1H16M10.963S",
        "PT1H21M16.044S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_26_degrees().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_16_1_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H8M43.656S",
        "PT1H8M47.245S",
        "PT1H8M41.543S",
        "PT1H8M48.093S",
        "PT1H35M51.891S",
        "PT1H12M48.804S",
        "PT1H13M30.311S",
        "PT1H9M5.083S",
        "PT1H13M53.327S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_16_1_degrees().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_60_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H5M20.649S",
        "PT1H6M44.464S",
        "PT1H6M20.067S",
        "PT1H6M12.03S",
        "None",
        "PT1H12M6.198S",
        "PT1H12M33.518S",
        "PT1H8M3.752S",
        "PT1H12M49.163S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_60_minutes().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_72_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H6M24.779S",
        "PT1H8M5.357S",
        "PT1H7M36.081S",
        "PT1H7M26.437S",
        "None",
        "PT1H14M31.438S",
        "PT1H15M4.221S",
        "PT1H9M40.502S",
        "PT1H15M22.996S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_72_minutes_zmanis().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_90_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H10M20.649S",
        "PT1H11M44.464S",
        "PT1H11M20.067S",
        "PT1H11M12.03S",
        "None",
        "PT1H17M6.198S",
        "PT1H17M33.518S",
        "PT1H13M3.752S",
        "PT1H17M49.163S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_90_minutes().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_90_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H9M10.812S",
        "PT1H10M55.58S",
        "PT1H10M25.084S",
        "PT1H10M15.038S",
        "None",
        "PT1H17M37.748S",
        "PT1H18M11.897S",
        "PT1H12M34.69S",
        "PT1H18M31.454S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_90_minutes_zmanis().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_96_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H10M6.156S",
        "PT1H11M52.321S",
        "PT1H11M21.419S",
        "PT1H11M11.239S",
        "None",
        "PT1H18M39.851S",
        "PT1H19M14.456S",
        "PT1H13M32.752S",
        "PT1H19M34.274S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_96_minutes_zmanis().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_ateret_torah() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H4M12.714S",
        "PT1H5M44.91S",
        "PT1H5M18.074S",
        "PT1H5M9.233S",
        "None",
        "PT1H11M38.818S",
        "PT1H12M8.869S",
        "PT1H7M12.127S",
        "PT1H12M26.08S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_ateret_torah().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_alos_16_1_to_tzeis_7_083() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H4M47.768S",
        "PT1H5M14.657S",
        "PT1H5M3.545S",
        "PT1H5M5.813S",
        "PT1H12M52.249S",
        "PT1H9M38.283S",
        "PT1H10M15.336S",
        "PT1H5M50.326S",
        "PT1H10M36.024S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_alos_16_1_to_tzeis_7_083().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_96_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H11M20.649S",
        "PT1H12M44.464S",
        "PT1H12M20.067S",
        "PT1H12M12.03S",
        "None",
        "PT1H18M6.198S",
        "PT1H18M33.518S",
        "PT1H14M3.752S",
        "PT1H18M49.163S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_96_minutes().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_120_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H15M20.649S",
        "PT1H16M44.464S",
        "PT1H16M20.067S",
        "PT1H16M12.03S",
        "None",
        "PT1H22M6.198S",
        "PT1H22M33.518S",
        "PT1H18M3.752S",
        "PT1H22M49.163S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_120_minutes().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_120_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H13M47.533S",
        "PT1H15M39.285S",
        "PT1H15M6.757S",
        "PT1H14M56.041S",
        "None",
        "PT1H22M48.264S",
        "PT1H23M24.69S",
        "PT1H17M25.003S",
        "PT1H23M45.551S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_120_minutes_zmanis().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_baal_hatanya() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT56M0.579S",
        "PT57M20.274S",
        "PT56M56.844S",
        "PT56M49.536S",
        "PT11M19.376S",
        "PT1H2M37.509S",
        "PT1H3M5.439S",
        "PT58M36.415S",
        "PT1H3M21.399S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_baal_hatanya().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_gra() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT55M20.649S",
        "PT56M44.464S",
        "PT56M20.067S",
        "PT56M12.03S",
        "None",
        "PT1H2M6.198S",
        "PT1H2M33.518S",
        "PT58M3.752S",
        "PT1H2M49.163S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_gra().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_shaah_zmanis_mga_72_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_duration_strs = [
        "PT1H7M20.649S",
        "PT1H8M44.464S",
        "PT1H8M20.067S",
        "PT1H8M12.03S",
        "None",
        "PT1H14M6.198S",
        "PT1H14M33.518S",
        "PT1H10M3.752S",
        "PT1H14M49.163S",
    ];

    for (czc, expected) in zip(cals, expected_duration_strs) {
        let actual = czc.shaah_zmanis_mga_72_minutes().map_or_else(
            || String::from("None"),
            |sd| {
                sd.round(
                    SignedDurationRound::new()
                        .smallest(Unit::Millisecond)
                        .mode(RoundMode::Trunc),
                )
                .unwrap()
                .to_string()
            },
        );
        assert_eq!(expected, actual)
    }
}
