// Generated by rust-zmanim-test-generator
// https://github.com/YSCohen/rust-zmanim-test-generator
// This file is part of rust-zmanim, licensed under LGPL-2.1

//! this is a set of tests for the solar azimuth and elevation functions of
//! [astronomical_calculator](rust_zmanim::astronomical_calculator) and
//! [ComplexZmanimCalendar](rust_zmanim::complex_zmanim_calendar::ComplexZmanimCalendar)

mod test_helper;
use jiff::{Timestamp, tz::TimeZone};
use rust_zmanim::astronomical_calculator;
use std::iter::zip;

/// Maximum acceptable variation, in degrees
const TOLERANCE: f64 = 1e-12;

fn instant() -> jiff::Zoned {
    "2017-10-17T12:34:56.789Z"
        .parse::<Timestamp>()
        .unwrap()
        .to_zoned(TimeZone::UTC)
}

#[test]
fn test_ac_solar_azimuth() {
    let items = test_helper::more_locations();
    let expected = [
        116.05867939111226,
        236.13340499050094,
        88.85746532828546,
        309.0553322707053,
        128.4069548223311,
        137.59677921118055,
        158.35311229203455,
        75.41291265680445,
        140.08268279166253,
    ];

    for (loc, exp) in zip(items, expected) {
        let actual = astronomical_calculator::solar_azimuth(&instant(), &loc);
        assert!(
            (actual - exp).abs() < TOLERANCE,
            "expected {exp}, got {actual}"
        );
    }
}

#[test]
fn test_ac_solar_elevation() {
    let items = test_helper::more_locations();
    let expected = [
        14.594843348108459,
        28.627203448307956,
        -18.69704888944546,
        -53.460243231402586,
        -4.265281034884908,
        -59.00052670245137,
        -61.037322267726836,
        -54.78417933319579,
        -53.8606409717936,
    ];

    for (loc, exp) in zip(items, expected) {
        let actual = astronomical_calculator::solar_elevation(&instant(), &loc);
        assert!(
            (actual - exp).abs() < TOLERANCE,
            "expected {exp}, got {actual}"
        );
    }
}

#[test]
fn test_czc_solar_azimuth() {
    let items = test_helper::more_locations_czcs(false);
    let expected = [
        116.05867939111226,
        236.13340499050094,
        88.85746532828546,
        309.0553322707053,
        128.4069548223311,
        137.59677921118055,
        158.35311229203455,
        75.41291265680445,
        140.08268279166253,
    ];

    for (czc, exp) in zip(items, expected) {
        let actual = czc.solar_azimuth(&instant());
        assert!(
            (actual - exp).abs() < TOLERANCE,
            "expected {exp}, got {actual}"
        );
    }
}

#[test]
fn test_czc_solar_elevation() {
    let items = test_helper::more_locations_czcs(false);
    let expected = [
        14.594843348108459,
        28.627203448307956,
        -18.69704888944546,
        -53.460243231402586,
        -4.265281034884908,
        -59.00052670245137,
        -61.037322267726836,
        -54.78417933319579,
        -53.8606409717936,
    ];

    for (czc, exp) in zip(items, expected) {
        let actual = czc.solar_elevation(&instant());
        assert!(
            (actual - exp).abs() < TOLERANCE,
            "expected {exp}, got {actual}"
        );
    }
}
