// Generated by rust-zmanim-test-generator
// https://github.com/YSCohen/rust-zmanim-test-generator
// This file is part of rust-zmanim, licensed under LGPL-2.1

//! this is a set of tests for the *shaah zmanis* methods of
//! [ComplexZmanimCalendar](rust_zmanim::complex_zmanim_calendar::ComplexZmanimCalendar),
//! using sea-level calculations.
//! Because KosherJava returns *shaah zmanis* values as `long` of milliseconds,
//! these tests only check for within 1 millisecond

mod test_helper;
use std::iter::zip;

/// assert that the two values are either both `None`, or both `Some` with the
/// values within 1 of each other
fn within_one(a: Option<i128>, b: Option<i128>) {
    match a {
        None => assert_eq!(b, None),
        Some(val_a) => {
            if let Some(val_b) = b {
                // assert they are within 1ms
                assert!((val_a - val_b).abs() < 2)
            } else {
                panic!()
            }
        }
    }
}

#[test]
fn test_shaah_zmanis_alos_16_1_to_tzeis_3_7() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(3798553),
        Some(3834368),
        Some(3821167),
        Some(3821830),
        Some(3818308),
        Some(4107270),
        Some(4142837),
        Some(3876885),
        Some(4162759),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_alos_16_1_to_tzeis_3_7()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_alos_16_1_to_tzeis_3_8() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(3801199),
        Some(3836747),
        Some(3823608),
        Some(3824319),
        Some(3837725),
        Some(4109366),
        Some(4144976),
        Some(3879059),
        Some(4164919),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_alos_16_1_to_tzeis_3_8()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_19_8_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4317265),
        Some(4301331),
        Some(4300103),
        Some(4310323),
        None,
        Some(4526376),
        Some(4572067),
        Some(4304389),
        Some(4597302),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_19_8_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_18_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4223015),
        Some(4216641),
        Some(4213227),
        Some(4221645),
        None,
        Some(4449606),
        Some(4493213),
        Some(4226918),
        Some(4517339),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_18_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_26_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4643865),
        Some(4593504),
        Some(4600050),
        Some(4616844),
        None,
        Some(4792749),
        Some(4846485),
        Some(4570963),
        Some(4876044),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_26_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_16_1_degrees() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4123656),
        Some(4127245),
        Some(4121543),
        Some(4128093),
        Some(5751891),
        Some(4368804),
        Some(4410311),
        Some(4145083),
        Some(4433327),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_16_1_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_60_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(3920608),
        Some(4004427),
        Some(3980030),
        Some(3971992),
        None,
        Some(4326169),
        Some(4353485),
        Some(4083718),
        Some(4369130),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_60_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_72_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(3984730),
        Some(4085312),
        Some(4056036),
        Some(4046390),
        None,
        Some(4471403),
        Some(4504182),
        Some(4180462),
        Some(4522956),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_72_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_90_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4220608),
        Some(4304427),
        Some(4280030),
        Some(4271992),
        None,
        Some(4626169),
        Some(4653485),
        Some(4383718),
        Some(4669130),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_90_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_90_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4150760),
        Some(4255534),
        Some(4225037),
        Some(4214990),
        None,
        Some(4657711),
        Some(4691856),
        Some(4354648),
        Some(4711413),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_90_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_96_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4206104),
        Some(4312274),
        Some(4281371),
        Some(4271190),
        None,
        Some(4719814),
        Some(4754414),
        Some(4412710),
        Some(4774232),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_96_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_ateret_torah() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(3852669),
        Some(3944870),
        Some(3918033),
        Some(3909191),
        None,
        Some(4298786),
        Some(4328833),
        Some(4032090),
        Some(4346043),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_ateret_torah()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_96_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4280608),
        Some(4364427),
        Some(4340030),
        Some(4331992),
        None,
        Some(4686169),
        Some(4713485),
        Some(4443718),
        Some(4729130),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_96_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_120_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4520608),
        Some(4604427),
        Some(4580030),
        Some(4571992),
        None,
        Some(4926169),
        Some(4953485),
        Some(4683718),
        Some(4969130),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_120_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_120_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4427478),
        Some(4539236),
        Some(4506706),
        Some(4495989),
        None,
        Some(4968225),
        Some(5004646),
        Some(4644958),
        Some(5025507),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_120_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_baal_hatanya() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(3360579),
        Some(3440274),
        Some(3416844),
        Some(3409536),
        Some(679376),
        Some(3757509),
        Some(3785439),
        Some(3516415),
        Some(3801399),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_baal_hatanya()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_gra() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(3320608),
        Some(3404427),
        Some(3380030),
        Some(3371992),
        None,
        Some(3726169),
        Some(3753485),
        Some(3483718),
        Some(3769130),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_gra()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_72_minutes() {
    let cals = test_helper::more_locations_czcs(false);
    let expected_datetime_strs = [
        Some(4040608),
        Some(4124427),
        Some(4100030),
        Some(4091992),
        None,
        Some(4446169),
        Some(4473485),
        Some(4203718),
        Some(4489130),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_72_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}
