// Generated by rust-zmanim-test-generator
// https://github.com/YSCohen/rust-zmanim-test-generator
// This file is part of rust-zmanim, licensed under LGPL-2.1

//! this is a set of tests for
//! [astronomical_calculator](rust_zmanim::astronomical_calculator)

mod test_helper;
use jiff::civil;
use rust_zmanim::astronomical_calculator;
use std::iter::zip;

#[test]
fn test_sunrise() {
    let locations = test_helper::more_locations();
    let expected_datetime_strs = [
        "2017-10-17 07:09:11.571 -0400",
        "2017-10-17 06:39:32.238 +0300",
        "2017-10-17 07:00:25.354 -0700",
        "2017-10-17 05:48:20.360 +0900",
        "None",
        "2017-10-17 06:54:18.595 +1400",
        "2017-10-17 05:33:07.634 +1200",
        "2017-10-17 07:28:06.821 -0900",
        "2017-10-17 05:46:39.708 -1100",
    ];

    for (loc, expected) in zip(locations, expected_datetime_strs) {
        let date = civil::date(2017, 10, 17);
        let actual = match astronomical_calculator::sunrise(date, &loc) {
            Some(dt) => dt.strftime("%Y-%m-%d %H:%M:%S.%3f %z").to_string(),
            None => String::from("None"),
        };
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_sea_level_sunrise() {
    let locations = test_helper::more_locations();
    let expected_datetime_strs = [
        "2017-10-17 07:09:51.403 -0400",
        "2017-10-17 06:43:42.820 +0300",
        "2017-10-17 07:01:45.127 -0700",
        "2017-10-17 05:49:21.432 +0900",
        "None",
        "2017-10-17 07:00:05.528 +1400",
        "2017-10-17 05:38:06.219 +1200",
        "2017-10-17 07:28:33.400 -0900",
        "2017-10-17 05:47:51.439 -1100",
    ];

    for (loc, expected) in zip(locations, expected_datetime_strs) {
        let date = civil::date(2017, 10, 17);
        let actual = match astronomical_calculator::sea_level_sunrise(date, &loc) {
            Some(dt) => dt.strftime("%Y-%m-%d %H:%M:%S.%3f %z").to_string(),
            None => String::from("None"),
        };
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_sunset() {
    let locations = test_helper::more_locations();
    let expected_datetime_strs = [
        "2017-10-17 18:14:38.994 -0400",
        "2017-10-17 18:08:46.815 +0300",
        "2017-10-17 18:19:05.657 -0700",
        "2017-10-17 17:04:46.827 +0900",
        "None",
        "2017-10-17 19:31:07.236 +1400",
        "2017-10-17 18:13:47.410 +1200",
        "2017-10-17 19:05:45.001 -0900",
        "2017-10-17 18:22:53.237 -1100",
    ];

    for (loc, expected) in zip(locations, expected_datetime_strs) {
        let date = civil::date(2017, 10, 17);
        let actual = match astronomical_calculator::sunset(date, &loc) {
            Some(dt) => dt.strftime("%Y-%m-%d %H:%M:%S.%3f %z").to_string(),
            None => String::from("None"),
        };
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_sea_level_sunset() {
    let locations = test_helper::more_locations();
    let expected_datetime_strs = [
        "2017-10-17 18:13:59.201 -0400",
        "2017-10-17 18:04:36.392 +0300",
        "2017-10-17 18:17:45.941 -0700",
        "2017-10-17 17:03:45.802 +0900",
        "None",
        "2017-10-17 19:25:19.911 +1400",
        "2017-10-17 18:08:48.435 +1200",
        "2017-10-17 19:05:18.428 -0900",
        "2017-10-17 18:21:41.407 -1100",
    ];

    for (loc, expected) in zip(locations, expected_datetime_strs) {
        let date = civil::date(2017, 10, 17);
        let actual = match astronomical_calculator::sea_level_sunset(date, &loc) {
            Some(dt) => dt.strftime("%Y-%m-%d %H:%M:%S.%3f %z").to_string(),
            None => String::from("None"),
        };
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_solar_noon() {
    let locations = test_helper::more_locations();
    let expected_datetime_strs = [
        "2017-10-17 12:42:12.781 -0400",
        "2017-10-17 12:24:22.754 +0300",
        "2017-10-17 12:39:59.750 -0700",
        "2017-10-17 11:26:48.756 +0900",
        "2017-10-17 12:04:26.192 -0400",
        "2017-10-17 13:12:36.880 +1400",
        "2017-10-17 11:53:19.765 +1200",
        "2017-10-17 13:17:04.390 -0900",
        "2017-10-17 12:04:38.204 -1100",
    ];

    for (loc, expected) in zip(locations, expected_datetime_strs) {
        let date = civil::date(2017, 10, 17);
        let actual = match astronomical_calculator::solar_noon(date, &loc) {
            Some(dt) => dt.strftime("%Y-%m-%d %H:%M:%S.%3f %z").to_string(),
            None => String::from("None"),
        };
        assert_eq!(expected, actual)
    }
}

#[test]
fn test_solar_midnight() {
    let locations = test_helper::more_locations();
    let expected_datetime_strs = [
        "2017-10-18 00:42:06.833 -0400",
        "2017-10-18 00:24:16.713 +0300",
        "2017-10-18 00:39:53.840 -0700",
        "2017-10-17 23:26:42.627 +0900",
        "2017-10-18 00:04:20.236 -0400",
        "2017-10-18 01:12:30.711 +1400",
        "2017-10-17 23:53:13.604 +1200",
        "2017-10-18 01:16:58.513 -0900",
        "2017-10-18 00:04:32.338 -1100",
    ];

    for (loc, expected) in zip(locations, expected_datetime_strs) {
        let date = civil::date(2017, 10, 17);
        let actual = match astronomical_calculator::solar_midnight(date, &loc) {
            Some(dt) => dt.strftime("%Y-%m-%d %H:%M:%S.%3f %z").to_string(),
            None => String::from("None"),
        };
        assert_eq!(expected, actual)
    }
}
