// Generated by rust-zmanim-test-generator
// https://github.com/YSCohen/rust-zmanim-test-generator
// This file is part of rust-zmanim, licensed under LGPL-2.1

//! this is a set of tests for the *shaah zmanis* methods of
//! [ComplexZmanimCalendar](rust_zmanim::complex_zmanim_calendar::ComplexZmanimCalendar),
//! using elevation-adjusted calculations.
//! Because KosherJava returns *shaah zmanis* values as `long` of milliseconds,
//! these tests only check for within 1 millisecond

mod test_helper;
use std::iter::zip;

/// assert that the two values are either both `None`, or both `Some` with the
/// values within 1 of each other
fn within_one(a: Option<i128>, b: Option<i128>) {
    match a {
        None => assert_eq!(b, None),
        Some(val_a) => {
            if let Some(val_b) = b {
                // assert they are within 1ms
                assert!((val_a - val_b).abs() < 2)
            } else {
                panic!()
            }
        }
    }
}

#[test]
fn test_shaah_zmanis_alos_16_1_to_tzeis_3_7() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(3798553),
        Some(3834368),
        Some(3821167),
        Some(3821830),
        Some(3818308),
        Some(4107270),
        Some(4142837),
        Some(3876885),
        Some(4162759),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_alos_16_1_to_tzeis_3_7()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_alos_16_1_to_tzeis_3_8() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(3801199),
        Some(3836747),
        Some(3823608),
        Some(3824319),
        Some(3837725),
        Some(4109366),
        Some(4144976),
        Some(3879059),
        Some(4164919),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_alos_16_1_to_tzeis_3_8()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_19_8_degrees() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4317265),
        Some(4301331),
        Some(4300103),
        Some(4310323),
        None,
        Some(4526376),
        Some(4572067),
        Some(4304389),
        Some(4597302),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_19_8_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_18_degrees() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4223015),
        Some(4216641),
        Some(4213227),
        Some(4221645),
        None,
        Some(4449606),
        Some(4493213),
        Some(4226918),
        Some(4517339),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_18_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_26_degrees() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4643865),
        Some(4593504),
        Some(4600050),
        Some(4616844),
        None,
        Some(4792749),
        Some(4846485),
        Some(4570963),
        Some(4876044),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_26_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_16_1_degrees() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4123656),
        Some(4127245),
        Some(4121543),
        Some(4128093),
        Some(5751891),
        Some(4368804),
        Some(4410311),
        Some(4145083),
        Some(4433327),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_16_1_degrees()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_60_minutes() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(3927251),
        Some(4046224),
        Some(3993335),
        Some(3982178),
        None,
        Some(4384088),
        Some(4403337),
        Some(4088152),
        Some(4381107),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_60_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_72_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(3992701),
        Some(4135468),
        Some(4072002),
        Some(4058613),
        None,
        Some(4540906),
        Some(4564004),
        Some(4185783),
        Some(4537328),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_72_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_90_minutes() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4227251),
        Some(4346224),
        Some(4293335),
        Some(4282178),
        None,
        Some(4684088),
        Some(4703337),
        Some(4388152),
        Some(4681107),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_90_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_90_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4159064),
        Some(4307780),
        Some(4241669),
        Some(4227722),
        None,
        Some(4730110),
        Some(4754171),
        Some(4360190),
        Some(4726384),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_90_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_96_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4214518),
        Some(4365217),
        Some(4298224),
        Some(4284092),
        None,
        Some(4793178),
        Some(4817560),
        Some(4418326),
        Some(4789402),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_96_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_ateret_torah() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(3859976),
        Some(3990846),
        Some(3932669),
        Some(3920396),
        None,
        Some(4362497),
        Some(4383670),
        Some(4036968),
        Some(4359218),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_ateret_torah()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_96_minutes() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4287251),
        Some(4406224),
        Some(4353335),
        Some(4342178),
        None,
        Some(4744088),
        Some(4763337),
        Some(4448152),
        Some(4741107),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_96_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_120_minutes() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4527251),
        Some(4646224),
        Some(4593335),
        Some(4582178),
        None,
        Some(4984088),
        Some(5003337),
        Some(4688152),
        Some(4981107),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_120_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_120_minutes_zmanis() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4436335),
        Some(4594965),
        Some(4524447),
        Some(4509570),
        None,
        Some(5045451),
        Some(5071116),
        Some(4650870),
        Some(5041476),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_120_minutes_zmanis()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_baal_hatanya() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(3360579),
        Some(3440274),
        Some(3416844),
        Some(3409536),
        Some(679376),
        Some(3757509),
        Some(3785439),
        Some(3516415),
        Some(3801399),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_baal_hatanya()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_gra() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(3327251),
        Some(3446224),
        Some(3393335),
        Some(3382178),
        None,
        Some(3784088),
        Some(3803337),
        Some(3488152),
        Some(3781107),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_gra()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}

#[test]
fn test_shaah_zmanis_mga_72_minutes() {
    let cals = test_helper::more_locations_czcs(true);
    let expected_datetime_strs = [
        Some(4047251),
        Some(4166224),
        Some(4113335),
        Some(4102178),
        None,
        Some(4504088),
        Some(4523337),
        Some(4208152),
        Some(4501107),
    ];

    for (czc, edt) in zip(cals, expected_datetime_strs) {
        let result = czc
            .shaah_zmanis_mga_72_minutes()
            .map_or_else(|| None, |sd| Some(sd.as_millis()));
        within_one(result, edt)
    }
}
